rmdir /s /q "./oss/clibs"
rmdir /s /q "./oss/conf"
rmdir /s /q "./oss/lapis_env"
rmdir /s /q "./oss/memleak"
del /Q ".\oss\*.bat"
del /Q ".\oss\*.exe"
del /Q ".\oss\*.exp"
del /Q ".\oss\*.pdb"
del /Q ".\oss\*.dll"
del /Q ".\oss\*.lib"
del /Q ".\oss\*.manifest"
del /Q ".\oss\*.chm"
